FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-env
WORKDIR /app
EXPOSE 80
EXPOSE 443

COPY src/api/BankingApi.csproj ./
RUN dotnet restore BankingApi.csproj

COPY src/api/ ./
RUN dotnet publish BankingApi.csproj -c Release -o out

FROM mcr.microsoft.com/dotnet/sdk:7.0
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "BankingApi.dll"]
