FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-env
WORKDIR /app

COPY src/api/BankingApi.csproj ./
RUN dotnet restore BankingApi.csproj
COPY src/api/ ./
RUN dotnet publish BankingApi.csproj -c Release -o out

FROM mcr.microsoft.com/dotnet/runtime:7.0 AS runtime
WORKDIR /app

COPY --from=build-env /app/out .

EXPOSE 80
EXPOSE 443

ENTRYPOINT ["dotnet", "BankingApi.dll"]
